### PR TITLE
Remove multi language page from official site.

### PR DESCRIPTION
**Pull request by repeatedly**
We can change $DEFAULT_LANGUAGE to each language for supporting
another language. Translation could be managed by forking repository and setup each language directory.

### CODE REVIEW

**Comment by repeatedly** [comment]
Currently, there are many outdated documents and some users hit troubles or refer outdated plugin parameters.
So removing contribution based translation from repository is good for users.

**Comment by repeatedly** [comment]
@frsyuki @kzk @kiyoto @mazgi How about this?
Keep each language directory to support other language.
If change `$DEFAULT_LANGUAGE` to `ja`, fluentd-docs uses `ja` directly content.
I think it is easy to merge master branch into own language repository.

**Comment by mazgi** [comment]
Is that publish the translated version website by fork an everyone the repository as the “language repository” in the future?

**Comment by repeatedly** [comment]
Everyone creates each language version and fluentd-docs can link to such site/repository as XXX language docs.

**Comment by kzk** [comment]
Please merge the change.

**Pull request merged**
