### PR TITLE
docs: Fix a typo (Dowload -> Download)

### PR DESCRIPTION
**Pull request by fujimotos**
This patch fixes a subtle typo in the manual.

This commit also includes  fixes for the old revisions of this document
(namely v0.10 and v0.12)

### CODE REVIEW

**Comment by repeatedly** [comment]
Thanks!

**Comment by repeatedly** [comment]
@fujimotos Your patches look good. How about becoming a maintainer of fluentd-docs?

**Comment by fujimotos** [comment]
> How about becoming a maintainer of fluentd-docs?

Thanks. I'd accept the maintainership of fluentd-docs.

Anyway, I've been planning to keep working on the fluentd documents for
a time to make them up-to-date (Nothing drastic, just plumbing-ish works)

I hope my work benefit the fluentd users who rely on these docs...

**Comment by repeatedly** [comment]
Thanks. I sent an invitation.

**Pull request merged**
