### PR TITLE
Add out_null document for v0.14

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by repeatedly** [comment]
Sorry. Could you use table for plugin parameters like this?

https://github.com/fluent/fluentd-docs/pull/345

**Comment by okkez** [comment]
The version field means that the parameter has been introduced since the version. Right?
For example, `never_flush` has been introduced since Fluentd v0.14.12.

Could you show me example about required parameter?
Can I just remove the column named default?

**Comment by repeatedly** [comment]
> For example, never_flush has been introduced since Fluentd v0.14.12.

yes and if it is introduce since v0.12, use v0.14.0.

> Can I just remove the column named default?

This needs a discussion.
Currently, I write `required parameter` in the column.
Removing column is confusing so filling text is better.
I think "Nothing (required parameter)" is more better.

**Comment by okkez** [comment]
> yes and if it is introduce since v0.12, use v0.14.0.

OK.

> Removing column is confused so filling text is better.
> I think "Nothing (required parameter)" is more better.

Agree.
But I want to write much simpler about required parameter.

How about following?

```
### param1 (required)

| type | default | version |
|:----:|:----:|:----:|
|string|Nothing|...|

Description here. (This is required value)

### param2

| type | default | version |
|:----:|:----:|:----:|
| string |value|...|

Description here. (This is optional value)

```

**Comment by repeatedly** [comment]
It is also good 👍

**Comment by okkez** [comment]
I see.
I've pushed changes.

**Pull request merged**
