### PR TITLE
syslog-influxdb: Add latest syslog with influxdb article

### PR DESCRIPTION
**Pull request by cosmo0920**
Prior article is https://www.fluentd.org/guides/recipes/syslog-influxdb.

I've rewrite "Syslog with InfluxDB" article.

Related to #566.

Signed-off-by: Hiroshi Hatake <hatake@clear-code.com>

### CODE REVIEW

**Comment by cosmo0920** [comment]
@fujimotos Could you take a look?
Currently, [syslog-influxdb](https://www.fluentd.org/guides/recipes/syslog-influxdb) is outdated.
We should provide up-to-date article about InfluxDB usage on Fluentd.

**Comment by fujimotos** [comment]
I'll find some time in this week and have a look at it.
Please wait a bit.

**Comment by fujimotos** [comment]
I'm looking at this patch and wondering: did you actually test this
article and make sure it works?

For example, won't this configuration fails to catch tags like
"rsyslog.foo.baa"?

https://github.com/fluent/fluentd-docs/pull/611/files#diff-ca4e5af7fe143f2988ad73897d346183R118

Another point. Why do we need to install Elasticsearch plugin manually
on td-agent3?

https://github.com/fluent/fluentd-docs/pull/611/files#diff-ca4e5af7fe143f2988ad73897d346183R60

I also see several links pointing to void (e.g. "/download") so please:

 1. Test this article yourself and confirm it works
 2. Make sure links in this article are consistent

Tell me if you have done them.

**Comment by fujimotos** [comment]
Merged. Thank you for contribution.

**Pull request merged**
