### PR TITLE
Add v14 articles 2

### PR DESCRIPTION
**Pull request by tagomoris**
Same with #228, but added a bug fix.

### CODE REVIEW

**Comment by repeatedly** [comment]
After merged this PR, desigin is broken.
Could you check the problem?

https://i.gyazo.com/52abc97bab779b5c0fd4d3d789bc80b1.png

**Comment by tagomoris** [comment]
Hmm, I'll check it later.

**Comment by tagomoris** [comment]
I pushed a fix for this on master.
@repeatedly could you release once again?

**Comment by repeatedly** [comment]
Deploy is automatically done by CI.

**Pull request merged**
