### PR TITLE
Add label section

### PR DESCRIPTION
**Pull request by repeatedly**
@sonots Do we need more use-cases?

### CODE REVIEW

**Comment by sonots** [comment]
Just an opinion: Personally, I often use `label` feature with following pattern:

```
   <source>
     @type forward
     @label @raw
   </source>

  <label @raw>
     <match **>
       type copy
       <store>
         @type relabel
         @label @es
       </store>
       <store>
         @type relabel
         @label @s3
       </store>
     </match>
   </label>

   <label @es>
     <filter **>
       @type record_transformer
       <record>
         # ...
       </record>
     </filter>
     <match **>
       @type elasticsearch
       # ...
     </match>
   </label>

   <label @s3>
     <filter **>
       @type grep
       # ...
     </filter>
     <match **>
       @type s3
       # ...
     </match>
   </label>
```

This pattern makes config file very neat, and I want to recommend users to use `label` like this.

**Comment by repeatedly** [comment]
Hmm... adding this configuration expands config-file article.
How about adding this to fluentd's example directory?

**Comment by sonots** [comment]
Hmm... fluentd's example directory is basically for development. I do not assume users will see it. 
It was just an opinion. I am okay to merge.

**Comment by repeatedly** [comment]
Merged. I will consider adding label use-case to docs.fluentd.org.

**Pull request merged**
